version: '3.8'

services:
  backend:
    container_name: BIANXI_API_SERVICE
    image: devstoni/bianxi-api:0.7.0
    ports:
      - '$HOST_PORT:$SERVER_PORT'
    environment:
      - spring.profiles.active=prod
      - SERVER_PORT=$SERVER_PORT
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    networks:
      - mysqldb
      - net
  
  frontend:
    container_name: BIANXI_FRONT_SERVICE
    image: devstoni/bianxi-front:0.1.4
    ports:
      - '$FRONT_HOST_PORT:$FRONT_PORT'
    environment:
      - HOST_ENDPOINT=$HOST_ENDPOINT
      - STRIPE_VISIBLE_KEY=$STRIPE_VISIBLE_KEY
      - GOOGLE_OAUTH_KEY=$GOOGLE_OAUTH_KEY
      - NEW_USER_DISCOUNT=$NEW_USER_DISCOUNT
      - FRONT_PORT=$FRONT_PORT
    stdin_open: true
    networks:
      - net

networks:
  mysqldb:
    external: true
  net:
    external: false
